version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - apt update
      - apt install bc -y
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - mkdir ~/.kube
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name DEV-DP-EKS-Virginia
  build:
    commands:
      - echo Build Starting on `date`
      - echo Building with mvn...
      - mvn clean package -Dmaven.test.skip=true
  post_build:
    commands:
      - DATE=`date`
      - echo Build completed on $DATE
      - java ./target/datacat_agent-0.0.1-SNAPSHOT.jar

cache: 
  paths: 
    - '/root/.m2/**/*'